"""DeepSeek-backed summarization pipeline.

Design (see MAINTENANCE.md for the full rationale):

  Stage 1 (map, batched)    -- turn each raw article into a short structured
                               Chinese summary + topic tag + importance score.
  Stage 2 (reduce, single)  -- merge/dedupe those summaries across sources
                               into themed sections with a top-line executive
                               summary.

Source URLs are NEVER generated by the model. Every article gets a
code-assigned `id` (see `Article.id`) before it reaches a prompt, the model
is only ever asked to echo that id back, and rendering resolves ids to real
URLs from data we fetched ourselves. Any id the model invents or drops is
logged and discarded rather than trusted -- this is what keeps "点击跳转到
原文" honest instead of hallucinated.

Both stages use `response_format={"type": "json_object"}` (DeepSeek's JSON
mode) with a fixed system-prompt prefix, so repeated calls within one run
benefit from DeepSeek's automatic prefix caching (see
https://api-docs.deepseek.com/guides/kv_cache) -- only the per-batch article
data changes between calls, the instructions/schema stay byte-identical.
"""
from __future__ import annotations

import json
import logging
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Callable

from openai import OpenAI

from .config import Settings
from .models import Article, ArticleSummary, Channel, Digest, DigestItem, DigestSection

logger = logging.getLogger(__name__)

ChatFn = Callable[[str, str, int], dict]


def _map_system_prompt(channel: Channel) -> str:
    """Stage-1 (map) system prompt, parameterized by channel so the same
    pipeline works for any topical digest, not just AI industry news.

    Kept as a pure function of `channel` (no per-run/per-batch variables) so
    it's a byte-identical prefix across every batch call for a channel in a
    given run -- see the module docstring on why that matters for DeepSeek's
    prefix cache.
    """
    topics_str = "、".join(channel.topics)
    return f"""你是一名{channel.domain_desc}编辑助手。你会收到若干条今天抓取到的原始文章（每条包含 id、来源、标题、正文节选）。
请为每一条文章生成结构化的 JSON 摘要，帮助读者快速理解要点。

严格要求：
- 只输出 JSON，不要输出任何多余文字。
- 顶层格式为 {{"items": [...]}}，items 数组每个元素对应输入的一条文章。
- 每个元素必须包含且仅包含这些字段：
  - "id": 必须原样复制输入中的 id 字段，不能修改或编造。
  - "headline_zh": 简体中文标题，不超过 30 字。
  - "summary_zh": 1-2 句简体中文摘要，客观陈述事实，不要加入你自己的评论。
  - "key_points_zh": 最多 3 条要点的字符串数组，可为空数组。
  - "topic_tag": 从这些标签中选一个最贴切的：{topics_str}。只有真正属于{channel.domain_desc}的行业资讯、
    技术前沿、产业报告这类实质内容才保留；以下情况一律标记为 "无关"（这类文章不会进入最终简报）：
    (a) 文章内容与{channel.domain_desc}完全无关（例如体育、娱乐八卦、与该领域无关的普通时政）；
    (b) 虽然提到该领域的公司/人物，但只是无实质行业信息量的琐碎内容 —— 例如高管个人财务纠纷/赔偿金额、
    个人官司、绯闻、日常琐事、无关痛痒的花边新闻；
    (c) 来源媒体平时会报道{channel.domain_desc}，但这篇具体文章其实是别的领域的内容（例如笼统的清洁能源/
    太阳能/地热/气候政策报道、笼统的 AI 商业模式讨论、日常消费类测评/试驾体验/怀旧车型对比等），
    不能因为"来源看起来相关"就放行，要看这篇文章本身是否围绕{channel.domain_desc}展开；
    (d) 单纯的产品评测、试驾体验、用户使用心得、图集、怀旧对比这类软性内容，即使标的物属于该领域，
    只要不包含行业层面的实质信息（新技术、新政策、新交易、新数据），也标记为 "无关"。
    "其他" 标签只用于确实与{channel.domain_desc}强相关、但现有具体分类都不合适的重要资讯，不是拿不准
    时随手丢进去的兜底选项——拿不准时优先按上面 (a)-(d) 的标准判断是否应为 "无关"。
  - "importance": 1-5 的整数，5 表示对该领域影响重大，1 表示价值较低的常规资讯；若 topic_tag 为 "无关"，importance 填 1 即可。
- 如果某条文章正文过短或无法判断内容，仍要基于标题给出合理的最佳猜测摘要，不要省略该 id。

示例输出：
{{"items": [{{"id": "src-abc1234567", "headline_zh": "示例标题", "summary_zh": "示例摘要。", "key_points_zh": ["要点一"], "topic_tag": "{channel.topics[0]}", "importance": 3}}]}}
"""


def _reduce_system_prompt(channel: Channel) -> str:
    """Stage-2 (reduce) system prompt, parameterized by channel. See
    `_map_system_prompt` for why this stays a pure function of `channel`."""
    return f"""你是一名{channel.domain_desc}日报主编。你会收到今天所有文章的结构化摘要列表（每条含 id、来源、标题、摘要、标签、重要性）。
请将它们整理成一份面向中文读者的每日{channel.domain_desc}简报大纲。

严格要求：
- 只输出 JSON，不要输出任何多余文字。
- 顶层格式：{{"executive_summary_zh": [...], "sections": [...]}}。
- "executive_summary_zh"：5-8 条字符串，今天最重要的要点速览（每条一句话）。
- "sections"：数组，每个元素为 {{"section_title_zh": "...", "items": [...]}}。
  - section_title_zh 是你归纳出的中文分类标题，相近主题请合并为同一个 section，不要输出重复或过于琐碎的分类。
  - 每个 section 内的 items 数组元素为 {{"headline_zh": "...", "synthesis_zh": "...", "source_ids": [...]}}。
    - headline_zh：合并后的中文标题。
    - synthesis_zh：2-4 句中文综述，如果多个来源报道同一件事，请融合成一段，不要重复罗列。
    - source_ids：该条目对应的原始文章 id 列表，必须是输入中真实出现过的 id，可以有多个（同一事件的不同来源），不能编造不存在的 id。
  - 按 importance 与新闻价值，将更重要的条目排在每个 section 前面；不重要的琐碎资讯可以合并或省略，但不要凭空丢弃 id 对应的信息，除非它确实价值很低。

示例输出：
{{"executive_summary_zh": ["示例要点一句话"], "sections": [{{"section_title_zh": "示例分类", "items": [{{"headline_zh": "示例", "synthesis_zh": "示例综述。", "source_ids": ["src-abc1234567"]}}]}}]}}
"""


MAP_MAX_TOKENS = 2200
REDUCE_MAX_TOKENS = 4000
MAX_RETRIES = 3


class DeepSeekUnavailable(RuntimeError):
    """Raised when the DeepSeek API can't be reached/authenticated."""


def make_chat_fn(settings: Settings) -> ChatFn:
    """Build the default ChatFn backed by the real DeepSeek API.

    Tests (and any future alternate backend) can pass their own `ChatFn` --
    a callable of (system_prompt, user_content, max_tokens) -> parsed JSON
    dict -- straight into `summarize_articles` / `build_digest` instead of
    calling this factory, which is how the LLM boundary stays mockable.
    """
    if not settings.has_api_key:
        raise DeepSeekUnavailable(
            "DEEPSEEK_API_KEY is not set. Copy .env.example to .env and fill it in."
        )
    client = OpenAI(api_key=settings.deepseek_api_key, base_url=settings.deepseek_base_url)

    def _chat(system_prompt: str, user_content: str, max_tokens: int) -> dict:
        last_error: Exception | None = None
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                response = client.chat.completions.create(
                    model=settings.deepseek_model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_content},
                    ],
                    response_format={"type": "json_object"},
                    temperature=0.3,
                    max_tokens=max_tokens,
                    timeout=settings.request_timeout,
                )
                content = response.choices[0].message.content or ""
                return json.loads(content)
            except json.JSONDecodeError as exc:
                last_error = exc
                logger.warning("DeepSeek returned non-JSON content (attempt %d): %s", attempt, exc)
            except Exception as exc:  # noqa: BLE001 - broad on purpose, see retry loop
                last_error = exc
                logger.warning("DeepSeek call failed (attempt %d/%d): %s", attempt, MAX_RETRIES, exc)
            time.sleep(min(2 ** attempt, 8))
        raise DeepSeekUnavailable(f"DeepSeek call failed after {MAX_RETRIES} attempts: {last_error}")

    return _chat


def _chunk(seq: list, size: int) -> list[list]:
    return [seq[i : i + size] for i in range(0, len(seq), size)]


def _map_batch(batch: list[Article], channel: Channel, chat_fn: ChatFn) -> list[ArticleSummary]:
    payload = {
        "articles": [
            {
                "id": a.id,
                "source": a.source_name,
                "title": a.title,
                "text": a.text[:4000] if a.text else "(无正文，请仅根据标题判断)",
            }
            for a in batch
        ]
    }
    user_content = "请为以下 JSON 数组中的每篇文章生成摘要：\n" + json.dumps(payload, ensure_ascii=False)

    by_id = {a.id: a for a in batch}
    summaries: list[ArticleSummary] = []
    try:
        result = chat_fn(_map_system_prompt(channel), user_content, MAP_MAX_TOKENS)
        items = result.get("items", []) if isinstance(result, dict) else []
    except DeepSeekUnavailable:
        logger.exception("map stage failed for a batch of %d article(s); using fallback summaries", len(batch))
        items = []

    seen_ids: set[str] = set()
    for item in items:
        article_id = item.get("id")
        article = by_id.get(article_id)
        if article is None:
            logger.warning("map stage returned unknown article id %r; discarding", article_id)
            continue
        seen_ids.add(article_id)
        summaries.append(
            ArticleSummary(
                article=article,
                headline_zh=str(item.get("headline_zh") or article.title)[:60],
                summary_zh=str(item.get("summary_zh") or ""),
                key_points_zh=[str(p) for p in item.get("key_points_zh", []) if p][:3],
                topic_tag=item.get("topic_tag") if item.get("topic_tag") in channel.topics else "其他",
                importance=_safe_importance(item.get("importance")),
            )
        )

    for article in batch:
        if article.id not in seen_ids:
            summaries.append(_fallback_summary(article))
    return summaries


def _safe_importance(value) -> int:
    try:
        return max(1, min(5, int(value)))
    except (TypeError, ValueError):
        return 3


def _fallback_summary(article: Article) -> ArticleSummary:
    """Used when the model drops an id or the whole call fails -- keeps the
    article visible in the digest (headline-only) instead of silently
    vanishing."""
    return ArticleSummary(
        article=article,
        headline_zh=article.title[:60],
        summary_zh="(摘要生成失败，仅显示原始标题)",
        key_points_zh=[],
        topic_tag="其他",
        importance=2,
    )


def summarize_articles(
    articles: list[Article], channel: Channel, settings: Settings, chat_fn: ChatFn | None = None
) -> list[ArticleSummary]:
    if not articles:
        return []
    chat_fn = chat_fn or make_chat_fn(settings)
    batches = _chunk(articles, settings.articles_per_batch)

    results: list[ArticleSummary] = []
    with ThreadPoolExecutor(max_workers=settings.max_concurrent_llm_calls) as pool:
        futures = [pool.submit(_map_batch, batch, channel, chat_fn) for batch in batches]
        for future in as_completed(futures):
            results.extend(future.result())
    return results


def _group_by_topic_fallback(summaries: list[ArticleSummary]) -> Digest:
    """Pure-code fallback used when the reduce call fails entirely: group by
    topic_tag with no cross-source merging. Degraded but never empty."""
    by_topic: dict[str, list[ArticleSummary]] = {}
    for s in sorted(summaries, key=lambda s: -s.importance):
        by_topic.setdefault(s.topic_tag, []).append(s)

    sections = [
        DigestSection(
            title_zh=topic,
            items=[DigestItem(headline_zh=s.headline_zh, synthesis_zh=s.summary_zh, sources=[s]) for s in items],
        )
        for topic, items in by_topic.items()
    ]
    top_highlights = [s.headline_zh for s in sorted(summaries, key=lambda s: -s.importance)[:6]]
    return Digest(
        date_str="",
        executive_summary_zh=top_highlights,
        sections=sections,
        source_count=len({s.article.source_name for s in summaries}),
        article_count=len(summaries),
    )


def build_digest(
    summaries: list[ArticleSummary],
    channel: Channel,
    date_str: str,
    settings: Settings,
    chat_fn: ChatFn | None = None,
) -> Digest:
    if not summaries:
        return Digest(
            date_str=date_str,
            executive_summary_zh=[],
            sections=[],
            source_count=0,
            article_count=0,
            channel_name=channel.name,
        )

    chat_fn = chat_fn or make_chat_fn(settings)
    by_id = {s.article.id: s for s in summaries}

    payload = {
        "articles": [
            {
                "id": s.article.id,
                "source": s.article.source_name,
                "title": s.headline_zh,
                "summary": s.summary_zh,
                "topic_tag": s.topic_tag,
                "importance": s.importance,
            }
            for s in summaries
        ]
    }
    user_content = "请整合以下所有文章摘要为每日简报大纲：\n" + json.dumps(payload, ensure_ascii=False)

    try:
        result = chat_fn(_reduce_system_prompt(channel), user_content, REDUCE_MAX_TOKENS)
    except DeepSeekUnavailable:
        logger.exception("reduce stage failed; falling back to plain topic grouping")
        digest = _group_by_topic_fallback(summaries)
        digest.date_str = date_str
        digest.channel_name = channel.name
        return digest

    sections: list[DigestSection] = []
    for raw_section in result.get("sections", []) if isinstance(result, dict) else []:
        items: list[DigestItem] = []
        for raw_item in raw_section.get("items", []):
            resolved = [by_id[i] for i in raw_item.get("source_ids", []) if i in by_id]
            missing = [i for i in raw_item.get("source_ids", []) if i not in by_id]
            if missing:
                logger.warning("reduce stage referenced unknown id(s) %s; dropping from item", missing)
            if not resolved:
                logger.warning("digest item %r had no valid sources after id check; skipping", raw_item.get("headline_zh"))
                continue
            items.append(
                DigestItem(
                    headline_zh=str(raw_item.get("headline_zh") or resolved[0].headline_zh),
                    synthesis_zh=str(raw_item.get("synthesis_zh") or resolved[0].summary_zh),
                    sources=resolved,
                )
            )
        if items:
            sections.append(DigestSection(title_zh=str(raw_section.get("section_title_zh") or "其他"), items=items))

    if not sections:
        logger.warning("reduce stage produced no usable sections; falling back to plain topic grouping")
        digest = _group_by_topic_fallback(summaries)
        digest.date_str = date_str
        digest.channel_name = channel.name
        return digest

    return Digest(
        date_str=date_str,
        executive_summary_zh=[str(x) for x in result.get("executive_summary_zh", [])],
        sections=sections,
        source_count=len({s.article.source_name for s in summaries}),
        article_count=len(summaries),
        channel_name=channel.name,
    )
